describe('Check form', () => {
    it('Check the form with valid credentiols', () => {
        cy.visit('https://demoqa.com/automation-practice-form')
        cy.get('header > a > img').should('be.exist')
        cy.get('#firstName').type('Sona')
        cy.get('#lastName').type('Margaryan')
        cy.get('#userEmail').type('smargaryan88@gmail.com')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(2)').click()
        cy.get('#userNumber').type('3720000000')
        cy.get('.subjects-auto-complete__value-container').type('no object')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3)').click()
        cy.get('.css-yk16xz-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click()
        //cy.wrap({ foo:'Uttar Pradesh' }).its('foo').should('eq', 'Uttar Pradesh')
        cy.get('#react-select-3-option-1').click()
        cy.get('#city > .css-yk16xz-control > .css-1hwfws3').click()
        //cy.wrap({ foo:'Agra' }).its('foo').should('eq', 'Agra')
        cy.get('#react-select-4-option-0').click()
        cy.get('#submit').click({force: true})
        cy.get('#closeLargeModal').click({force: true})
    })
})

it.only('Check the form with invalid credentiols', () => {
    cy.visit('https://demoqa.com/automation-practice-form')
    cy.get('header > a > img').should('be.exist')
    cy.get('#firstName').type('Sona').clear()
    cy.get('#lastName').type('Margaryan').clear()
    cy.get('#userEmail').type('smargaryan88@gmail.com').clear()
    cy.get('#genterWrapper > .col-md-9 > :nth-child(2)').click()
    cy.get('#userNumber').type('3720000000').clear()
    cy.get('.subjects-auto-complete__value-container').type('no object')
    cy.get('.css-yk16xz-control > .css-1wy0on6 > .css-tlfecz-indicatorContainer').click()
    //cy.wrap({ foo:'Uttar Pradesh' }).its('foo').should('eq', 'Uttar Pradesh')
    cy.get('#react-select-3-option-1').click()
    cy.get('#city > .css-yk16xz-control > .css-1hwfws3').click()
    //cy.wrap({ foo:'Agra' }).its('foo').should('eq', 'Agra')
    cy.get('#react-select-4-option-0').click()
    cy.get('#submit').click({force: true})
    cy.get('#closeLargeModal').click({force: false})
})
